### ISSUE TITLE
Executed trades showing up in the wrong page

### ISSUE THREAD

**Issue by marsface** [ripple/ripplecharts-frontend#121]
Im using chrome 48.xxxx and I noticed some orders executed at XRP/USD are showing up in XRP/BRL. The wrong data disappears after I refresh the page.
Pictures:
![usd](https://cloud.githubusercontent.com/assets/12703634/13410639/a638aaac-df17-11e5-9f7c-78c9a563a742.png) ![brl](https://cloud.githubusercontent.com/assets/12703634/13410640/a8b818ee-df17-11e5-8204-ca108d15324d.png)

**Comment by shekenahglory** [comment]
should be fixed https://github.com/ripple/ripplecharts-frontend/commit/b79f2bd63d2d75feca4d13dc5769e7088b81a7e8 re-open if you see it again
