### ISSUE TITLE
Ripplecharts documentation

### ISSUE THREAD

**Issue by sathishparam** [ripple/ripplecharts-frontend#167]
Hi,

     I was looking for documentation to understand the different charts available in ripplecharts website. I was specifically looking for ways to pull cross border money transfer using ILP. is that available through ripple charts or data.ripple.com? Please advise. 

Regards,
Sathish

**Comment by scratch28** [comment]
ILP transfers using the XRP ledger will be part of the ledger
Currently there are no indicators whether the transaction is sourced or using ILP vs standard RippleD interface. 
ILP transfers independent of the XRP ledger are not tracked through XRP charts nor do we currently collect that information
