### ISSUE TITLE
value server URL in config?

### ISSUE THREAD

**Issue by datasmithtech** [ripple/ripplecharts-frontend#173]
good day.

i am interested in learning this, and i tried running this web app, however, i believe i am using the incorrect default url.
   "server": "wss://s1.ripple.com:443"

What value should it be?

**Comment by Nicholas-Mwaura** [comment]
what should this value be? Tried  the following and non is working
"server": "wss://s1.ripple.com:443" 
"server":"wss://s1.ripple.com"
"https://data.ripple.com/v2"

**Comment by shekenahglory** [comment]
you should have something like 
```  "production": {
    "ga_account"  : "",
    "ga_id"       : "",
    "api"         : "https://data.ripple.com/v2",
    "domain"      : "http://ripplecharts.com",
    "maintenance" : false
  }
}
```

in `deployment.environments.json` and

```
Options = {
  theme     : "dark",
  base      : {currency:"XRP", issuer:""},
  counter   : {currency:"USD", issuer:"rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B"},
  chartType : "candlestick",
  interval  : "30m",
  range     : "3d",

  ripple    : {
    "server": "wss://s1.ripple.com:443"
  }
}
``` 
in `src/config.js`

**Comment by nickle-back** [comment]
Hi Matthew,
The configuration settings worked thank you . If you don't mind please check out this page on xrpcharts
 
https://xrpcharts.ripple.com/#/topology

it's stuck on August 17. I've been checking it out for about a week and the very same entries keep being displayed.I think the validator listing is also showing august 17.

**Comment by scratch28** [comment]
This has been addressed and is now up to date
