### ISSUE TITLE
Run ripple charts on local server

### ISSUE THREAD

**Issue by tuloski** [ripple/ripplecharts-frontend#181]
Hi,
is there any documentation/pointer on how to run ripple chart with a local server?
Is a rippled enough or a special node (for bigger history) is needed? Does rippled support natively data API v2?

**Comment by scratch28** [comment]
RippleCharts requires a backend that rippleD cannot support
That back end can be found here.  https://github.com/ripple/rippled-historical-database
This extracts the notional data out of rippleD and replicates them to be queryable forms intended for  high volume reads and analytics.   
The RippleD API are for simple informational queries regarding a transaction or account, not for heavy extrapolation.  This backend was developed to relieve RippleD the burden of that heavy queries.   Charts just sits on top as an easy way to consume the data.
