### ISSUE TITLE
lowercase transaction hash gives "transaction not found" while uppercase transaction hash works when searching for transaction.

### ISSUE THREAD

**Issue by rawmaterials** [ripple/ripplecharts-frontend#183]
hi.,

i have tried it multiple times., 

here 
https://xrpcharts.ripple.com/#/transactions

if i enter lowercase transaction hash
**a34e2773dc21916870fe86e83b0b9a3f05bf2c64496264e2a764797a98eb38d0**

 then it says 

**transaction not found**

but if i enter same hash in **UPPERCASE**

**A34E2773DC21916870FE86E83B0B9A3F05BF2C64496264E2A764797A98EB38D0**

i can see the transaction.

please fix this., as exchange like poloniex gives hash in lowercase.

so every time i have to make hash to **UPPERCASE** and then search for it.

Hope this helps.,

Thanks & R.egards.

**Comment by shekenahglory** [comment]
fixed

**Comment by rawmaterials** [comment]
Thank you.
