### ISSUE TITLE
Stored XSS in transaction explorer

### ISSUE THREAD

**Issue by WietseWind** [ripple/ripplecharts-frontend#188]
Transaction:
```
{
  "TransactionType": "Payment",
  "Account": "rPdvC6ccq8hCdPKSPJkPmyZ4Mi1oG2FFkT",
  "Fee": 10,
  "Destination": "rPEPPER7kfTD9w2To4CQk6UCfuHM9c6GDY",
  "DestinationTag": 495,
  "Amount": 1234,
  "Memos": [
    {
      "Memo": {
        "MemoData": "48692C206A757374203C623E74657374696E673C2F623E203B29"
      }
    }
  ]
}
```

The *MemoData* is the HEX representation of (utf8 to hex):
`Hi, just <b>testing</b> ;)`

Sample:
https://xrpcharts.ripple.com/#/transactions/0180D1F07F31240E1D4E7503913885672E3227D8CC41600B4BD054FF01D6B2B6

The decoded hex is bold:
![image](https://user-images.githubusercontent.com/4756161/40650299-3ffed822-6333-11e8-90a7-01695c14c34a.png)

**Comment by shekenahglory** [comment]
fixed https://github.com/ripple/ripplecharts-frontend/commit/c0bf7032f9c115527562b3ef255fef18a91574ef
