### ISSUE TITLE
Xrp transaction failed "tecUNFUNDED_PAYMENT"

### ISSUE THREAD

**Issue by hv5609** [ripple/ripplecharts-frontend#193]
How to get my xrp back? As transaction is faild showing "tecUNFUNDED_PAYMENT"
But balance is deducted from my XRP wallet! Please help me!
Transaction ID is giving below-
C03BF9B4504F3195D47F8623DB7E24BD00143E2CA0F87F454F9393C8B704B97A

**Comment by hv5609** [comment]
Please help

**Comment by intelliot** [comment]
`tecUNFUNDED_PAYMENT` means that the transaction failed and the only balance deducted from the XRP wallet was the transaction fee of 0.1 XRP. No other balance was deducted.

```
AFFECTED LEDGER NODES:
It affected 1 nodes in the ledger:
MODIFIED NODES:
It modified the AccountRoot node of r9QA3mVFQ7V4CE8uGVaeGGDGgeAFc8rsPF
Balance reduced by 0.1 from 23,243.680133 to 23,243.580133 XRP
```

**Comment by zh3nz1dan** [comment]
F7E16EB29A52F97B23C1B3E81DDD5A089A2C56D8589AF95687D7D389ED4A635E
help me cancel the recharging order, I haven't received it in 4 days
![Screenshot_16](https://user-images.githubusercontent.com/48862267/54868107-6e85db00-4dbb-11e9-8e41-974c6f1fea35.png)

**Comment by romarjerhazremy** [comment]
missing number at the end is number eight. Pls help me.
![Screenshot_20200210_100533](https://user-images.githubusercontent.com/50799115/74116092-ce69a980-4b66-11ea-800b-6314ce5050b4.jpg)[My destination tag is 164188 pls help me](https://xrpcharts.ripple.com/#/transactions/3C8D6DA59C9666A9CAFC080F1ECA1719417342E683F930E66652F76A11D5A00F) 

![received_874634312976590](https://user-images.githubusercontent.com/50799115/74115976-5c916000-4b66-11ea-996b-c02b7f2a1d5f.jpeg)

**Comment by romarjerhazremy** [comment]
Pls pls help me
![IMG_20200210_100026](https://user-images.githubusercontent.com/50799115/74116206-5780e080-4b67-11ea-8611-8e3c79e819d2.JPG)

**Comment by avln** [comment]
I'm not sure who you are and what help you need

**Comment by romarjerhazremy** [comment]
Im Romeo Caladiao brave browser user i have bat token i am from brave
publisher now my withdrawal from xrp the problem in not entering xrp
wallet i because of lack of number eight at end destination tag. maybe
you can help me get my 75 bat token into my wallet xrp. here is my xrp
wallet rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
164188

**Comment by avln** [comment]
Thee issue is you can not send dat to xrp address dat has to be converted
first to xrp

**Comment by romarjerhazremy** [comment]
that he is xrp the problem is not coming to xrp wallet i earn because the
reason i gave destination tag is missing a number

**Comment by Godwin1961** [comment]
PLEASE WHAT CAN BE DONE ABOUT THIS, THE RIPPLE SENT IS NOT REFLECTING AND IT HAS NOT BE RETRACTED
05C135F5DE71E396373E0D6DE44E77C955A3FCDA3918B72A5246937F0C11EC21
GO
DESCRIPTIONRAW
STATUS:
This transaction failed with a status code of tecUNFUNDED_PAYMENT, and validated in ledger 57248130 on August 2, 2020 10:52 PM UTC.
DESCRIPTION:
This is a Payment transaction.
The payment is from rHxsZo42NrTq1hC9dcnS8KAuvc8LrNdbpn to rsRy14FvipgqudiGmptJBhr1RtpsgfzKMM.
The payment has a destination tag: 1736847995
It was instructed to deliver 68.5143 XRP.
The transaction's sequence number is 610
MEMOS:
The transaction has no memos.
TRANSACTION COST:
Sending this transaction consumed 0.000012 XRP.
FLAGS:
The transaction specified the following flags:
tfFullyCanonicalSig
AFFECTED LEDGER NODES:
It affected 1 nodes in the ledger:
MODIFIED NODES:
It modified the AccountRoot node of rHxsZo42NrTq1hC9dcnS8KAuvc8LrNdbpn
Balance reduced by 0.000012 from 27.30687 to 27.306858 XRP

**Comment by bbyuna28** [comment]
please help me also . my xrp is not yet in my coins

**Comment by intelliot** [comment]
`tecUNFUNDED_PAYMENT` means that the transaction failed because the sending account is trying to send more XRP than it holds, not counting the reserve. https://xrpl.org/tec-codes.html

If you have some other problem, open a new issue instead of replying this one.
