### ISSUE TITLE
HTML Injection through transaction memo

### ISSUE THREAD

**Issue by symfonyaml** [ripple/ripplecharts-frontend#196]
In the transaction below:
https://xrpcharts.ripple.com/#/transactions/7A93EE437A3FE7973900E54E35C4360E97ED174427AA1EBEDDBBCFEF66DBCB57

The initial memo content is `<h1>THIS PAGE RENDERS HTML` and the HTML is rendered.
It looks like the Memo type can also have HTML Injection.
![rrrrr](https://user-images.githubusercontent.com/8001284/50570207-bfdd8a00-0dcb-11e9-851e-2f20888a974c.png)

**Comment by WietseWind** [comment]
As mentioned here, confirmed it was fixed. https://github.com/ripple/ripplecharts-frontend/issues/188

**Comment by symfonyaml** [comment]
> As mentioned here, confirmed it was fixed. #188

**Comment by WietseWind** [comment]
@symfonyaml The problem is back though.

**Comment by symfonyaml** [comment]
@WietseWind right... Looks like` filterXSS()` doesnt filter HTML anymore?
BTW how come the last release of this repo was on 6 Jan 2017 ?

**Comment by WietseWind** [comment]
@symfonyaml Maybe rolling (commit) releases instead of Github releases? There is commit activity:
`Latest commit 1d789ad  on 29 Nov 2018`

**Comment by symfonyaml** [comment]
@WietseWind yes I saw the recent commits. What I meant is that I am surprised that the GitHub release feature was not used for 2 years now.

**Comment by intelliot** [comment]
The sanitizer had whitelisted a few HTML tags like `h1` and `b`. This whitelist has been removed, so the problem is now fixed. Thanks for reporting this!
