### ISSUE TITLE
tecUNFUNDED_PAYMENT ISSUE

### ISSUE THREAD

**Issue by victoryjoel** [ripple/ripplecharts-frontend#208]
I transferred 307.2424 xrp to a receivers wallet address and he is yet to receive it I checked in the blocking network it shows tecUNFUNDED_PAYMET
MY WALLET ADDRESS
rHxsZo42NrTq1hC9dcnS8KAuvc8LrNdbpn
MY XRP TAG
332532391

RECEIVER WALLET ADDRESS
rsRy14FvipgqudiGmptJBhr1RtpsgfzKMM

Receivet xrp tag
3691141836
Amount send
307.2424
Time stamp
December 21,2020, 9:13pm
Transaction hash
650E6801889B010F1418535D20F27285E0369BFE56F1048B51F8252877718FF5

**Comment by eth7777** [comment]
> XRP please

address
rpct6vuKL2bcJq9FFygAsYNMVXyXirwPeL

tag
63528688

**Comment by intelliot** [comment]
`tecUNFUNDED_PAYMENT` means that the transaction failed because the sending account is trying to send more XRP than it holds, not counting the reserve. https://xrpl.org/tec-codes.html

Hope this helps
