### ISSUE TITLE
Ripple failed transaction

### ISSUE THREAD

**Issue by bamxy** [ripple/ripplecharts-frontend#211]
STATUS:
This transaction failed with a status code of tecUNFUNDED_PAYMENT, and validated in ledger 61719435 on February 20, 2021 10:42 PM UTC.
DESCRIPTION:
This is a Payment transaction.
The payment is from rHxsZo42NrTq1hC9dcnS8KAuvc8LrNdbpn to rsRy14FvipgqudiGmptJBhr1RtpsgfzKMM.
The payment has a destination tag: 2955086828
It was instructed to deliver 239.99 XRP.
The transaction's sequence number is 25993.
MEMOS:
The transaction has no memos.
TRANSACTION COST:
Sending this transaction consumed 0.006054 XRP.
FLAGS:
The transaction specified the following flags:
tfFullyCanonicalSig
AFFECTED LEDGER NODES:
It affected 1 nodes in the ledger:
MODIFIED NODES:
It modified the AccountRoot node of rHxsZo42NrTq1hC9dcnS8KAuvc8LrNdbpn
Balance reduced by 0.006054 from 20.711092 to 20.705038 XRP

**Comment by intelliot** [comment]
`tecUNFUNDED_PAYMENT` means that the transaction failed because the sending account is trying to send more XRP than it holds, not counting the reserve. https://xrpl.org/tec-codes.html

Hope this helps

**Comment by bamxy** [comment]
How can I get back my 240 ripple
