### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hserang** [ripple/ripplecharts-frontend#93]
### Description
Market detail intermittently displays.
If it does display, clicking on the "max" range of a chart does nothing.
Console displays: "Uncaught TypeError: Cannot read property 'click' of null"

### Steps to Reproduce
* goto chart detail by clicking on a chart in the top view, or goto http://www.ripplecharts-staging.com/#/markets
* It there is no chart, there will be an undefined error in the console
* If the chart shows, click on the max range - it will not change the view and will console.log the error

**Comment by shekenahglory** [comment]
I believe this is fixed, re-open if you are still seeing it
